server:
  port: 8001
spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=authentication-service
    hikari:
      username: postgres
      password: root
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 1200000
      connection-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update